### Site Settings ###
title: Donovan Said
description: >-
  Hi, I'm Donovan, and this is my space, where you can hopefully learn a little bit about myself,
  my professional experience and interests.
baseurl: ""
repository: donovan-said/donovan-said.github.io
remote_theme: YoussefRaafatNasry/portfolYOU
open_new_tab: true

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name: Donovan Said
  image: /img/profile_pic.jpg
  email: donovan.s.said@gmail.com
  github: donovan-said
  linkedin: donovansaid
  spotify: donovan.s.said

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###
disqus:
  shortname: DSP

### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: your-google-tracking-id

### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."
  description: "Support me on Buy me a coffee!"

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

### Exclude from processing ###
exclude:
  - Dockerfile
  - docker-compose.yml
  - docker-entrypoint.sh
  - README.md
  - CONTRIBUTING.md
  - CHANGELOG.md
  - LICENSE
  - "*.log"
